[package]
name = "rust_head"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert_cmd = "2.0.5"
clap = { version = "4.0.18", features = ["derive"] }
predicates = "2.1.1"
rand = "0.8.5"
